# Generated by EVN ALPHA Blocks from blink.evnblocks. Edit the blocks, not this file: it is rewritten at every run.

from evn import wait, battery, led


for count in range(10):
    led.toggle()
    wait(250)
led.off()
print(''.join([str(x) for x in ['battery: ', battery.voltage(), ' mV']]))
