# Generated by EVN ALPHA Blocks from first_moves.evnblocks. Edit the blocks, not this file: it is rewritten at every run.

from evn import Motor, Stop, wait

motor_1 = Motor(1)


print('angle at start: ' + str(motor_1.angle()))
motor_1.run_angle(500, 360)
print('after one turn: ' + str(motor_1.angle()))
motor_1.run_target(500, 0)
motor_1.run(300)
wait(1000)
print(''.join([str(x) for x in ['speed: ', motor_1.speed(), ' load: ', motor_1.load()]]))
motor_1.run_time(300, 800, then=Stop.COAST)
motor_1.stop()
print('finished')
